dubbo:
  registry:
    protocol: zookeeper
    address: 192.168.188.156:2181
  protocol:
    port: 20881
    name: dubbo
  application:
    name: myprovider
    qos-enable: false
  scan:
    basePackages: com.offcn.service
